# Generated by Django 4.0.2 on 2022-12-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Стоимость контейнера')),
                ('user_id', models.IntegerField(verbose_name='ID клиента')),
            ],
            options={
                'verbose_name': 'Карточка контейнера',
                'verbose_name_plural': 'Контейнеры',
            },
        ),
        migrations.CreateModel(
            name='ManagerCallRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=60, verbose_name='ФИО')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Время поступления заявки')),
                ('time_called', models.DateTimeField(auto_now=True, verbose_name='Время ответа на заявку')),
                ('status', models.BooleanField(default=False, verbose_name='Выполнен')),
            ],
            options={
                'verbose_name': 'Запрос на обратный звонок',
                'verbose_name_plural': 'Запросы на обратный звонок',
            },
        ),
    ]
