# Generated by Django 4.0.2 on 2022-12-19 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='user_id',
        ),
        migrations.AddField(
            model_name='container',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='container',
            name='rent_deadline',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата окончания аренды'),
            preserve_default=False,
        ),
    ]
