# Generated by Django 4.0.2 on 2022-12-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_container_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='loaded',
            field=models.BooleanField(default=False),
        ),
    ]
