# Generated by Django 4.0.2 on 2022-12-19 21:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_container_loaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='dimensions',
            field=models.CharField(default=django.utils.timezone.now, max_length=8, verbose_name='Габариты контейнера'),
            preserve_default=False,
        ),
    ]
